# 开发环境配置
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux_demo_dev
    username: webflux_user
    password: webflux_password
    properties:
      serverTimezone: Asia/Shanghai
      useUnicode: true
      characterEncoding: utf8mb4
  
  data:
    redis:
      enabled: true  # 开发环境启用Redis
      host: localhost
      port: 6379

logging:
  level:
    com.javalaabs.webflux: DEBUG
    org.springframework.data.r2dbc: DEBUG
    root: INFO

# 开发环境下显示详细的SQL日志
---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
